// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iymjygiqrtjeoljlzzgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5bWp5Z2lxcnRqZW9samx6emdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjE1NDYsImV4cCI6MjA3MDA5NzU0Nn0.z9j3Z7o1-iEpMKUDx-p7-1o-qiQXtc1sbTc7bvLYZwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});